services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper # nessessary?
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      test: ["CMD-SHELL", "nc localhost 2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  
  broker:
    image: confluentinc/cp-kafka
    hostname: broker # nessessary?
    container_name: broker
    depends_on:
        zookeeper:
          condition: 'service_healthy'
    ports:
      - "29092:29092"
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
        KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:9092, EXTERNAL_SAME_HOST://localhost:29092
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  connector:
    image: confluentinc/cp-kafka-connect-base
    command: 
      - bash 
      - -c
      - confluent-hub install --no-prompt confluentinc/kafka-connect-s3:latest && /etc/confluent/docker/run && sleep infinity

    hostname: connector
    container_name: connector
    ports:
      - "8083:8083"
    depends_on:
      - zookeeper
      - broker
    volumes:
      - $PWD/credentials:/root/.aws/credentials
      - $PWD/connectors:/connectors
    environment:
        CONNECT_BOOTSTRAP_SERVERS: 'broker:9092'
        CONNECT_REST_PORT: 8083
        CONNECT_GROUP_ID: "quickstart"
        CONNECT_CONFIG_STORAGE_TOPIC: "quickstart-config"
        CONNECT_OFFSET_STORAGE_TOPIC: "quickstart-offsets"
        CONNECT_STATUS_STORAGE_TOPIC: "quickstart-status"
        CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        CONNECT_REST_ADVERTISED_HOST_NAME: localhost
        CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components
        CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
        CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
        CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
  

  python:
    image: python:3.11
    container_name: python
    working_dir: /usr/src/app
    volumes:
      - $PWD/requirements.txt:/usr/src/app/requirements.txt
      - $PWD/kafka:/usr/src/app/kafka
    command: bash -c "pip install --no-cache-dir -r requirements.txt && python ./kafka/producer.py"
